name: "@appwarden/build-cloudflare-action"
branding:
  icon: cloud
  color: orange
description: Easy-to-use GitHub Action to build Appwarden for deployment to your Cloudflare domain
author: Appwarden <https://github.com/appwarden>
inputs:
  debug:
    description: Enable debug mode. Defaults to 'false'.
    default: false
  hostname:
    required: true
    type: string
    description: The hostname of your Appwarden-protected domain
  cloudflare-account-id:
    required: true
    type: string
    description: Cloudflare account id
runs:
  using: node20
  main: dist/index.js
