export interface HostnameConfig {
  lockPageSlug?: string
  debug?: boolean
  contentSecurityPolicy?: {
    mode?: "disabled" | "report-only" | "enforced"
    directives?: Record<string, string>
  }
}

export type GeneratedConfig = Record<string, HostnameConfig>

/**
 * Per-hostname middleware options returned from the API.
 * This is separate from ApiMiddlewareOptions which only contains global options.
 */
export type HostnameMiddlewareOptions = {
  "lock-page-slug"?: string
  "csp-mode"?: "disabled" | "report-only" | "enforced"
  "csp-directives"?: Record<string, string>
  debug?: string | boolean
}

export interface HydratedGeneratedConfig {
  configString: string
  hostnames: string[]
  debug: boolean
}

/**
 * Extracts hostnames from the generated config.
 * Hostnames are the top-level keys in the config object.
 */
export const extractHostnamesFromConfig = (
  config: GeneratedConfig,
): string[] => {
  return Object.keys(config)
}

export const hydrateGeneratedConfig = (
  middlewareOptionsMap: Map<string, HostnameMiddlewareOptions>,
): HydratedGeneratedConfig => {
  const config: GeneratedConfig = {}

  // Extract debug value - if ANY hostname has debug enabled, enable it globally
  let debug = false
  for (const [, options] of middlewareOptionsMap) {
    if (options?.debug) {
      // Handle both string "true"/"false" and boolean values
      const debugValue =
        typeof options.debug === "string"
          ? options.debug.toLowerCase() === "true"
          : options.debug
      if (debugValue) {
        debug = true
        break // Once we find one enabled, we can stop
      }
    }
  }

  // Build config with all properties nested under each hostname
  for (const [hostname, options] of middlewareOptionsMap) {
    const hostnameConfig: HostnameConfig = {}

    // Add lock-page-slug if present
    if (options?.["lock-page-slug"]) {
      hostnameConfig.lockPageSlug = options["lock-page-slug"]
    }

    // Add debug if present
    if (options?.debug !== undefined) {
      // Handle both string "true"/"false" and boolean values
      const debugValue =
        typeof options.debug === "string"
          ? options.debug.toLowerCase() === "true"
          : options.debug
      hostnameConfig.debug = debugValue
    }

    // Add contentSecurityPolicy if present
    if (options?.["csp-mode"] || options?.["csp-directives"]) {
      hostnameConfig.contentSecurityPolicy = {}
      if (options?.["csp-mode"]) {
        hostnameConfig.contentSecurityPolicy.mode = options["csp-mode"]
      }
      if (options?.["csp-directives"]) {
        hostnameConfig.contentSecurityPolicy.directives =
          options["csp-directives"]
      }
    }

    // Only add hostname to config if it has at least one property
    if (Object.keys(hostnameConfig).length > 0) {
      config[hostname] = hostnameConfig
    }
  }

  const hostnames = extractHostnamesFromConfig(config)

  const configString = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = ${JSON.stringify(config, null, 2)}
`

  return { configString, hostnames, debug }
}

export const generatedConfigTemplate = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = {}
`
