import { describe, expect, it } from "vitest"
import {
  extractHostnamesFromConfig,
  HostnameMiddlewareOptions,
  hydrateGeneratedConfig,
} from "./generated-config"

const header = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

`

describe("generated-config", () => {
  describe("hydrateGeneratedConfig", () => {
    it("should generate config with all properties nested for a single hostname", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance",
    "contentSecurityPolicy": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should generate config for multiple hostnames", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
        [
          "staging.example.com",
          {
            "lock-page-slug": "/staging-maintenance",
            "csp-mode": "report-only",
            "csp-directives": { "script-src": "'unsafe-inline'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance",
    "contentSecurityPolicy": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  },
  "staging.example.com": {
    "lockPageSlug": "/staging-maintenance",
    "contentSecurityPolicy": {
      "mode": "report-only",
      "directives": {
        "script-src": "'unsafe-inline'"
      }
    }
  }
}
`)
      expect(result.hostnames).toContain("app.example.com")
      expect(result.hostnames).toContain("staging.example.com")
      expect(result.hostnames).toHaveLength(2)
    })

    it("should generate empty config when no options are provided", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        ["app.example.com", {}],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {}
`)
      expect(result.hostnames).toEqual([])
    })

    it("should only include lockPageSlug when lock-page-slug is present", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance"
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should only include contentSecurityPolicy when csp options are present", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "contentSecurityPolicy": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should include contentSecurityPolicy with only mode when directives are missing", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "report-only",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "contentSecurityPolicy": {
      "mode": "report-only"
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should include contentSecurityPolicy with only directives when mode is missing", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "contentSecurityPolicy": {
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should generate empty config when no middleware options exist", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>()

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {}
`)
      expect(result.hostnames).toEqual([])
      expect(result.debug).toBe(false)
    })

    it("should extract debug value as boolean true when set to boolean true", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: true,
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(true)
    })

    it("should include debug field in generated config when debug is true", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: true,
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance",
    "debug": true
  }
}
`)
      expect(result.debug).toBe(true)
    })

    it("should include debug field in generated config when debug is false", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: false,
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance",
    "debug": false
  }
}
`)
      expect(result.debug).toBe(false)
    })

    it("should include debug field for only the hostname that has it configured", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: true,
          },
        ],
        [
          "staging.example.com",
          {
            "lock-page-slug": "/staging-maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "app.example.com": {
    "lockPageSlug": "/maintenance",
    "debug": true
  },
  "staging.example.com": {
    "lockPageSlug": "/staging-maintenance"
  }
}
`)
      expect(result.debug).toBe(true)
    })

    it("should extract debug value as boolean true when set to string 'true'", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: "true",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(true)
    })

    it("should extract debug value as boolean false when set to string 'false'", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: "false",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(false)
    })

    it("should extract debug value as boolean false when set to boolean false", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: false,
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(false)
    })

    it("should enable debug if ANY hostname has debug enabled", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            debug: false,
          },
        ],
        [
          "staging.example.com",
          {
            "lock-page-slug": "/staging-maintenance",
            debug: true,
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(true)
    })

    it("should default debug to false when not specified", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.debug).toBe(false)
    })
  })

  describe("extractHostnamesFromConfig", () => {
    it("should extract hostnames from config with lockPageSlug only", () => {
      const config = {
        "app.example.com": { lockPageSlug: "/maintenance" },
      }

      expect(extractHostnamesFromConfig(config)).toEqual(["app.example.com"])
    })

    it("should extract hostnames from config with contentSecurityPolicy only", () => {
      const config = {
        "app.example.com": {
          contentSecurityPolicy: { mode: "enforced" as const },
        },
      }

      expect(extractHostnamesFromConfig(config)).toEqual(["app.example.com"])
    })

    it("should extract all hostnames from config with multiple hostnames", () => {
      const config = {
        "app.example.com": {
          lockPageSlug: "/maintenance",
          contentSecurityPolicy: { mode: "enforced" as const },
        },
        "staging.example.com": {
          contentSecurityPolicy: { mode: "report-only" as const },
        },
      }

      const hostnames = extractHostnamesFromConfig(config)
      expect(hostnames).toContain("app.example.com")
      expect(hostnames).toContain("staging.example.com")
      expect(hostnames).toHaveLength(2)
    })

    it("should return empty array for empty config", () => {
      expect(extractHostnamesFromConfig({})).toEqual([])
    })
  })
})
