import { ApiMiddlewareOptions } from "../types"

export interface GeneratedConfig {
  appwarden?: Record<string, { lockPageSlug: string }>
  csp?: Record<
    string,
    {
      mode?: "disabled" | "report-only" | "enforced"
      directives?: Record<string, string>
    }
  >
}

export const hydrateGeneratedConfig = (
  hostnames: string[],
  middlewareOptionsMap: Map<string, ApiMiddlewareOptions>,
): string => {
  const config: GeneratedConfig = {}

  // Build appwarden multidomainConfig if any hostname has lock-page-slug
  const appwardenConfig: Record<string, { lockPageSlug: string }> = {}
  // Build CSP config per hostname
  const cspConfig: Record<
    string,
    {
      mode?: "disabled" | "report-only" | "enforced"
      directives?: Record<string, string>
    }
  > = {}

  for (const hostname of hostnames) {
    const options = middlewareOptionsMap.get(hostname)

    if (options?.["lock-page-slug"]) {
      appwardenConfig[hostname] = {
        lockPageSlug: options["lock-page-slug"],
      }
    }

    if (options?.["csp-mode"] || options?.["csp-directives"]) {
      cspConfig[hostname] = {}
      if (options?.["csp-mode"]) {
        cspConfig[hostname].mode = options["csp-mode"]
      }
      if (options?.["csp-directives"]) {
        cspConfig[hostname].directives = options["csp-directives"]
      }
    }
  }

  if (Object.keys(appwardenConfig).length > 0) {
    config.appwarden = appwardenConfig
  }

  if (Object.keys(cspConfig).length > 0) {
    config.csp = cspConfig
  }

  return `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = ${JSON.stringify(config, null, 2)}
`
}

export const generatedConfigTemplate = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = {}
`

