import { describe, expect, it } from "vitest"
import {
  extractHostnamesFromConfig,
  HostnameMiddlewareOptions,
  hydrateGeneratedConfig,
} from "./generated-config"

const header = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

`

describe("generated-config", () => {
  describe("hydrateGeneratedConfig", () => {
    it("should generate config with appwarden and csp for a single hostname", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    }
  },
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should generate config for multiple hostnames", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
        [
          "staging.example.com",
          {
            "lock-page-slug": "/staging-maintenance",
            "csp-mode": "report-only",
            "csp-directives": { "script-src": "'unsafe-inline'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    },
    "staging.example.com": {
      "lockPageSlug": "/staging-maintenance"
    }
  },
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    },
    "staging.example.com": {
      "mode": "report-only",
      "directives": {
        "script-src": "'unsafe-inline'"
      }
    }
  }
}
`)
      expect(result.hostnames).toContain("app.example.com")
      expect(result.hostnames).toContain("staging.example.com")
      expect(result.hostnames).toHaveLength(2)
    })

    it("should generate empty config when no options are provided", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        ["app.example.com", {}],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {}
`)
      expect(result.hostnames).toEqual([])
    })

    it("should only include appwarden config when lock-page-slug is present", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should only include csp config when csp options are present", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should include csp config with only mode when directives are missing", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "report-only",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "mode": "report-only"
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should include csp config with only directives when mode is missing", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
      expect(result.hostnames).toEqual(["app.example.com"])
    })

    it("should generate empty config when no middleware options exist", () => {
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>()

      const result = hydrateGeneratedConfig(middlewareOptionsMap)

      expect(result.configString).toBe(`${header}export const config = {}
`)
      expect(result.hostnames).toEqual([])
    })
  })

  describe("extractHostnamesFromConfig", () => {
    it("should extract hostnames from appwarden config only", () => {
      const config = {
        appwarden: {
          "app.example.com": { lockPageSlug: "/maintenance" },
        },
      }

      expect(extractHostnamesFromConfig(config)).toEqual(["app.example.com"])
    })

    it("should extract hostnames from csp config only", () => {
      const config = {
        csp: {
          "app.example.com": { mode: "enforced" as const },
        },
      }

      expect(extractHostnamesFromConfig(config)).toEqual(["app.example.com"])
    })

    it("should deduplicate hostnames from both configs", () => {
      const config = {
        appwarden: {
          "app.example.com": { lockPageSlug: "/maintenance" },
        },
        csp: {
          "app.example.com": { mode: "enforced" as const },
          "staging.example.com": { mode: "report-only" as const },
        },
      }

      const hostnames = extractHostnamesFromConfig(config)
      expect(hostnames).toContain("app.example.com")
      expect(hostnames).toContain("staging.example.com")
      expect(hostnames).toHaveLength(2)
    })

    it("should return empty array for empty config", () => {
      expect(extractHostnamesFromConfig({})).toEqual([])
    })
  })
})
