import { describe, expect, it } from "vitest"
import {
  HostnameMiddlewareOptions,
  hydrateGeneratedConfig,
} from "./generated-config"

const header = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

`

describe("generated-config", () => {
  describe("hydrateGeneratedConfig", () => {
    it("should generate config with appwarden and csp for a single hostname", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    }
  },
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
    })

    it("should generate config for multiple hostnames", () => {
      const hostnames = ["app.example.com", "staging.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
        [
          "staging.example.com",
          {
            "lock-page-slug": "/staging-maintenance",
            "csp-mode": "report-only",
            "csp-directives": { "script-src": "'unsafe-inline'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    },
    "staging.example.com": {
      "lockPageSlug": "/staging-maintenance"
    }
  },
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    },
    "staging.example.com": {
      "mode": "report-only",
      "directives": {
        "script-src": "'unsafe-inline'"
      }
    }
  }
}
`)
    })

    it("should generate empty config when no options are provided", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        ["app.example.com", {}],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {}
`)
    })

    it("should only include appwarden config when lock-page-slug is present", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    }
  }
}
`)
    })

    it("should only include csp config when csp options are present", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "enforced",
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "mode": "enforced",
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
    })

    it("should include csp config with only mode when directives are missing", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-mode": "report-only",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "mode": "report-only"
    }
  }
}
`)
    })

    it("should include csp config with only directives when mode is missing", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "csp-directives": { "default-src": "'self'" },
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "csp": {
    "app.example.com": {
      "directives": {
        "default-src": "'self'"
      }
    }
  }
}
`)
    })

    it("should handle hostname with no matching options in map", () => {
      const hostnames = ["app.example.com", "unknown.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>([
        [
          "app.example.com",
          {
            "lock-page-slug": "/maintenance",
          },
        ],
      ])

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {
  "appwarden": {
    "app.example.com": {
      "lockPageSlug": "/maintenance"
    }
  }
}
`)
    })

    it("should generate empty config when hostnames have no options", () => {
      const hostnames = ["app.example.com"]
      const middlewareOptionsMap = new Map<string, HostnameMiddlewareOptions>()

      const result = hydrateGeneratedConfig(hostnames, middlewareOptionsMap)

      expect(result).toBe(`${header}export const config = {}
`)
    })
  })
})
