export interface GeneratedConfig {
  appwarden?: Record<string, { lockPageSlug: string }>
  csp?: Record<
    string,
    {
      mode?: "disabled" | "report-only" | "enforced"
      directives?: Record<string, string>
    }
  >
}

/**
 * Per-hostname middleware options returned from the API.
 * This is separate from ApiMiddlewareOptions which only contains global options.
 */
export type HostnameMiddlewareOptions = {
  "lock-page-slug"?: string
  "csp-mode"?: "disabled" | "report-only" | "enforced"
  "csp-directives"?: Record<string, string>
}

export interface HydratedGeneratedConfig {
  configString: string
  hostnames: string[]
}

/**
 * Extracts deduplicated hostnames from the generated config.
 * Hostnames are derived from both appwarden and csp config keys.
 */
export const extractHostnamesFromConfig = (
  config: GeneratedConfig,
): string[] => {
  const hostnameSet = new Set<string>()

  if (config.appwarden) {
    Object.keys(config.appwarden).forEach((hostname) =>
      hostnameSet.add(hostname),
    )
  }

  if (config.csp) {
    Object.keys(config.csp).forEach((hostname) => hostnameSet.add(hostname))
  }

  return Array.from(hostnameSet)
}

export const hydrateGeneratedConfig = (
  middlewareOptionsMap: Map<string, HostnameMiddlewareOptions>,
): HydratedGeneratedConfig => {
  const config: GeneratedConfig = {}

  // Build appwarden multidomainConfig if any hostname has lock-page-slug
  const appwardenConfig: Record<string, { lockPageSlug: string }> = {}
  // Build CSP config per hostname
  const cspConfig: Record<
    string,
    {
      mode?: "disabled" | "report-only" | "enforced"
      directives?: Record<string, string>
    }
  > = {}

  for (const [hostname, options] of middlewareOptionsMap) {
    if (options?.["lock-page-slug"]) {
      appwardenConfig[hostname] = {
        lockPageSlug: options["lock-page-slug"],
      }
    }

    if (options?.["csp-mode"] || options?.["csp-directives"]) {
      cspConfig[hostname] = {}
      if (options?.["csp-mode"]) {
        cspConfig[hostname].mode = options["csp-mode"]
      }
      if (options?.["csp-directives"]) {
        cspConfig[hostname].directives = options["csp-directives"]
      }
    }
  }

  if (Object.keys(appwardenConfig).length > 0) {
    config.appwarden = appwardenConfig
  }

  if (Object.keys(cspConfig).length > 0) {
    config.csp = cspConfig
  }

  const hostnames = extractHostnamesFromConfig(config)

  const configString = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = ${JSON.stringify(config, null, 2)}
`

  return { configString, hostnames }
}

export const generatedConfigTemplate = `// This file is auto-generated by @appwarden/build-cloudflare-action
// Do not edit manually

export const config = {}
`
